;; coding look
(add-to-list 'custom-theme-load-path "~/.emacs.d/emacs-color-theme-solarized")
(load-theme 'solarized-dark t)
(set-face-attribute 'default nil :font "Consolas" :height 113)
(global-hl-line-mode 1)
(setq line-number-mode t)
(setq column-number-mode t)
(setq indent-tabs-mode nil)
(setq-default tab-width 3)
(electric-pair-mode t)

;; gui
(scroll-bar-mode -1)
(menu-bar-mode -1)
(tool-bar-mode -1)

;; behavior
(windmove-default-keybindings 'meta)
(global-set-key (kbd "C-x C-b") 'ibuffer)
(ido-mode t)
(iswitchb-mode t)
(setq iswitchb-buffer-ignore '("^ " "*Buffer"))
(setq iswitchb-buffer-ignore '("^\\*"))
(fset 'yes-or-no-p 'y-or-n-p)
(savehist-mode 1)
(setq frame-title-format "%b - Emacs")
(setq icon-title-format "%b - Emacs")
(setq require-final-newline 't)
(show-paren-mode t)
(require 'paren)
(set-face-background 'show-paren-match-face (face-background 'default))
(set-face-foreground 'show-paren-match-face "#def")
(set-face-attribute 'show-paren-match-face nil :weight 'extra-bold)
(setq show-paren-style 'parenthesis)
(setq x-stretch-cursor t)
(transient-mark-mode t)
(delete-selection-mode t)
